### PR TITLE
Handle DataStructure::makePath errors

### LINKED ISSUE #127: DataStructure::makePath leaves it in an incomplete state on failure
`DataStructure::makePath` creates intermediate paths as it needs them which will persist on failure which may be unexpected. It also doesn't check if the result of some it's casts which can lead to segfaults/undefined behavior on failure.

### PR DESCRIPTION
**Pull request by mmarineBlueQuartz**
Removes created DataPaths if DataStructure::makePath causes an error.

Fixes #127

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `complex/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `complex/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

### CODE REVIEW

**Review by nyoungbq — APPROVED** [review]

File: src/complex/DataStructure/DataStructure.cpp [hunk 1]
```diff
@@ -167,17 +169,24 @@ Result<LinkedPath> DataStructure::makePath(const DataPath& path)
...
+      createdIds.push_back(data->getId());
     }
     const BaseGroup* parent = dynamic_cast<const BaseGroup*>(data);
     pathIds.push_back(data->getId());
 
     for(usize i = 1; i < path.getLength(); i++)
     {
+      if(parent == nullptr)
+      {
+        return complex::MakeErrorResult<LinkedPath>(-3, "Target parent object in path is not derived from BaseGroup.");
```
Comment (imikejackson) [inline src/complex/DataStructure/DataStructure.cpp]: Please incorporate the "path" argument into the error message. This will help the user/developer better diagnose what is going wrong.

File: src/complex/DataStructure/DataStructure.cpp [hunk 2]
```diff
@@ -187,6 +196,11 @@ Result<LinkedPath> DataStructure::makePath(const DataPath& path)
     return {LinkedPath(this, pathIds)};
   } catch(const std::exception& e)
   {
+    for(const auto& id : createdIds)
+    {
+      removeData(id);
+    }
+
     return complex::MakeErrorResult<LinkedPath>(-2, "Exception thrown when attempting to create a path in the DataStructure");
```
Comment (imikejackson) [inline src/complex/DataStructure/DataStructure.cpp]: Please also incorporate that actual value of 'path' into the error message. If there are ways to better determine the type of exception thrown that would also help in the error message.

**Review by imikejackson — CHANGES_REQUESTED** [review]

File: src/complex/DataStructure/DataStructure.cpp (hunk 1 above)
Comment (nyoungbq) [inline src/complex/DataStructure/DataStructure.cpp]:
```suggestion
        return complex::MakeErrorResult<LinkedPath>(-3, fmt::format("Target parent object {} in path {} is not derived from BaseGroup.", name, path.toString()));
```

File: src/complex/DataStructure/DataStructure.cpp (hunk 2 above)
Comment (nyoungbq) [inline src/complex/DataStructure/DataStructure.cpp]:
```suggestion
    return complex::MakeErrorResult<LinkedPath>(-2, fmt::format("Exception thrown when attempting to create a path in the DataStructure: {}", e.what()));
```

**Review by nyoungbq — APPROVED** [review]
