### PR TITLE
BUG/API: Histogram Sync

### LINKED ISSUE #1044: Histogram Generation between 2 filters do not agree
The filters "Calculate Frequency Histogram" and "Compute Attribute Array Statistics" do not agree on a computed histogram.

Ideally, both filters should use the exact same function to generate the histogram.

You can use the Small IN100 feature data that is generated from the "(01) Small IN100 Morphological Statistics". Use both filters to generate histograms for the "Volume Sizes" array.

## Issue 0: Extract out the Histogram Generation Function into a Utility class

The DREAM3D-NX application should be able to call this utility function with an STL compatible container to generate the histogram.

## Issue 1: Compute Attribute Array Statistics needs to store the histogram bins

The frequencies are generated but not the actual bin ranges. This filter needs to be updated to include the bin ranges. The format of the output data should be the exact same as the "Calculate Frequency Histogram" filter produces.

## Issue 2: Compute Attribute Array Statistics needs more documentation for the histogram

The docs need to indicate what the histogram options do. Better yet would be to use the same options (or as close as possible) to the "Calculate Frequency Histogram"

## Issue 3: Compute Attribute Array Statistics Histogram options should be consistent with Calculate Frequency Histogram

These 2 filters are doing the same thing (for parts), they should have the same options worded in the same way for the filters.

## Issue 4: Additional Options (At least internally) when generating the Histogram

Currently the stand-alone filter saves the upper value of each bin but that is all. Maybe we should be saving both the lower and upper bounds for each bin in the array. This can come in handy when trying to create a plot (as in the DREAM3DNX capability) where we need to know the range of each bin. Just knowing the upper or lower probably isn't enough to work out the complete bin ranges.

## Example output from the Small IN100 Volume Sizes.

Screenshot 2024-08-08 at 11 37 50

### PR DESCRIPTION
**Pull request by nyoungbq**
fixes #1044 

## Naming Conventions

Naming of variables should descriptive where needed. Loop Control Variables can use `i` if warranted. Most of these conventions are enforced through the clang-tidy and clang-format configuration files. See the file `simplnx/docs/Code_Style_Guide.md` for a more in depth explanation.

## Filter Checklist

The help file `simplnx/docs/Porting_Filters.md` has documentation to help you port or write new filters. At the top is a nice checklist of items that should be noted when porting a filter.

## Unit Testing

The idea of unit testing is to test the filter for proper execution and error handling. How many variations on a unit test each filter needs is entirely dependent on what the filter is doing. Generally, the variations can fall into a few categories:

- [ ] 1 Unit test to test output from the filter against known exemplar set of data
- [ ] 1 Unit test to test invalid input code paths that are specific to a filter. Don't test that a DataPath does not exist since that test is already performed as part of the SelectDataArrayAction.

## Code Cleanup
- [ ] No commented out code (rare exceptions to this is allowed..)
- [ ] No API changes were made (or the changes have been approved)
- [ ] No major design changes were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added license to new files (if any)
- [ ] Added example pipelines that use the filter
- [ ] Classes and methods are properly documented

### CODE REVIEW

**Review by imikejackson — APPROVED** [review]

File: src/simplnx/DataStructure/IDataStore.hpp [hunk 1]
```diff
@@ -73,6 +73,15 @@ class SIMPLNX_EXPORT IDataStore
     return getNumberOfTuples() * getNumberOfComponents();
   }
 
+  /**
+   * @brief Returns the number of values stored within the DataStore.
+   * @return usize
+   */
+  usize size() const
+  {
+    return getNumberOfTuples() * getNumberOfComponents();
```
Comment (JDuffeyBQ) [inline src/simplnx/DataStructure/IDataStore.hpp]:
```suggestion
    return getSize();
```
We can implement `size()` using `getSize()`.

File: src/simplnx/Utilities/HistogramUtilities.hpp [hunk 2]
```diff
@@ -0,0 +1,347 @@
...
+  FillBinRanges(binRangesStore, rangeMinMax, numBins, increment);
+
+  for(usize i = 0; i < inputStore.size(); i++)
+  {
+    if(shouldCancel)
+    {
+      return MakeErrorResult(-23763, fmt::format("HistogramUtilities::{}: Signal Interrupt Received. {}:{}", __func__, __FILE__, __LINE__));
+    }
+    const auto bin = CalculateBin(inputStore[i], rangeMinMax.first, increment);
+    if((bin >= 0) && (bin < numBins))
```
Comment (JDuffeyBQ) [inline src/simplnx/Utilities/HistogramUtilities.hpp:134]: `bool` histograms should probably be a special case.

**Review by JDuffeyBQ — CHANGES_REQUESTED** [review]

**Review by imikejackson — APPROVED** [review]

**Review by JDuffeyBQ — APPROVED** [review]
