### PR TITLE
ENH: Fixes high memory consumption in SurfaceNets Filter

### LINKED ISSUE #1154: Surface Nets uses HUGE amounts of memory versus QuickMesh.
Was shown an example of trying to mesh some "Parts" out of a 1400 x 1400 x 1300 image geometry and the SurfaceNets filter spiked the memory to almost 128GB of RAM. This should be investigated to figure out what part of the SurfaceNets algorithm is taking up the memory and if that can be fixed.

### PR DESCRIPTION
**Pull request by imikejackson**
- DOC: Fixes incorrect human name for QuickMesh filter
- MEM: Reduces memory usage for SurfaceNets filter
- SPELL: Fixes misspellings in human facing error messages

### CODE REVIEW

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 1]
```diff
@@ -136,12 +142,12 @@ void MMCellFlag::set(int32_t cellLabels[8])
...
 }
 
-unsigned char MMCellFlag::numJunctions() const
-{
-  return m_numJunctions;
-}
+// unsigned char numJunctions() const
+//{
+//   return m_numJunctions;
+// }
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 2]
```diff
@@ -8,15 +8,21 @@
...
+//: m_bitFlag(0)
+//{
+//}
+// ~MMCellFlag()
+//{
+//}
+// void clear(unsigned int& bitflag)
+//{
+//  bitflag = 0;
+//}
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 3]
```diff
@@ -8,15 +8,21 @@
...
 
-void MMCellFlag::set(int32_t cellLabels[8])
+void set(unsigned int& m_bitFlag, unsigned char& m_numJunctions, int32_t cellLabels[8])
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]: These args should not have the member variable naming scheme in a free function

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 4]
```diff
@@ -136,12 +142,12 @@ void MMCellFlag::set(int32_t cellLabels[8])
...
-{
-  return m_numJunctions;
-}
+// unsigned char numJunctions() const
+//{
+//   return m_numJunctions;
+// }
 
-MMCellFlag::VertexType MMCellFlag::vertexType()
+VertexType vertexType(unsigned int& m_bitFlag)
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]: This arg should not have the member variable naming scheme in a free function

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 5]
```diff
@@ -10,119 +10,116 @@
...
-  // Get components of the cell flag
-  VertexType vertexType();
-  FaceCrossingType faceCrossingType(Face face);
-  bool isEdgeCrossing(Edge edge);
-  unsigned char numJunctions() const;
+// Get components of the cell flag
+VertexType vertexType(unsigned int& m_bitFlag);
+FaceCrossingType faceCrossingType(unsigned int& m_bitFlag, Face face);
+bool isEdgeCrossing(unsigned int& m_bitFlag, Edge edge);
+// unsigned char numJunctions() ;
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 6]
```diff
@@ -10,119 +10,116 @@
...
+// bottom-to-top (i.e., left-back-bottom vertex first and right-front-top vertex
+// last). Clearing the cell flag encodes types NoVertex, NoFaceCrossing, and no
+// edge or face crossings.
+void set(unsigned int& m_bitFlag, unsigned char& m_numJunctions, int32_t cellLabels[8]);
 
-  void clear()
-  {
-    m_bitFlag = 0;
-  }
+//  void clear(unsigned int& bitflag);
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 7]
```diff
@@ -10,119 +10,116 @@
...
-  // bottom-to-top (i.e., left-back-bottom vertex first and right-front-top vertex
-  // last). Clearing the cell flag encodes types NoVertex, NoFaceCrossing, and no
-  // edge or face crossings.
-  void set(int32_t cellLabels[8]);
+// Set components of the cell flag. The components are determined from the
+// cell labels of its 8 vertices, which are listed left-to-right, back-to-front,
+// bottom-to-top (i.e., left-back-bottom vertex first and right-front-top vertex
+// last). Clearing the cell flag encodes types NoVertex, NoFaceCrossing, and no
+// edge or face crossings.
+void set(unsigned int& m_bitFlag, unsigned char& m_numJunctions, int32_t cellLabels[8]);
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
void set(unsigned int& bitFlag, unsigned char& numJunctions, int32_t cellLabels[8]);
```
remove member variable naming scheme in free function args

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 8]
```diff
@@ -10,119 +10,116 @@
...
 
-  // Get components of the cell flag
-  VertexType vertexType();
-  FaceCrossingType faceCrossingType(Face face);
-  bool isEdgeCrossing(Edge edge);
-  unsigned char numJunctions() const;
+// Get components of the cell flag
+VertexType vertexType(unsigned int& m_bitFlag);
+FaceCrossingType faceCrossingType(unsigned int& m_bitFlag, Face face);
+bool isEdgeCrossing(unsigned int& m_bitFlag, Edge edge);
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
VertexType vertexType(unsigned int& bitFlag);
FaceCrossingType faceCrossingType(unsigned int& bitFlag, Face face);
bool isEdgeCrossing(unsigned int& bitFlag, Edge edge);
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 9]
```diff
@@ -10,119 +10,116 @@
...
 
-class MMCellFlag
+namespace MMCellFlag
 {
-public:
-  MMCellFlag();
-  virtual ~MMCellFlag();
+// public:
+//   MMCellFlag();
+//   virtual ~MMCellFlag();
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 10]
```diff
@@ -10,119 +10,116 @@
...
-  }
+//  void operator=(const MMCellFlag& t)
+//  {
+//    m_bitFlag = t.m_bitFlag;
+//  }
+//
+//  unsigned int getBitFlag() const
+//  {
+//    return m_bitFlag;
+//  }
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h [hunk 11]
```diff
@@ -10,119 +10,116 @@
...
-  {
-    VertexTypeShift = 0,
-    LeftFaceShift = 2,
-    RightFaceShift = 4,
-    BackFaceShift = 6,
-    FrontFaceShift = 8,
-    BottomFaceShift = 10,
-    TopFaceShift = 12,
-  };
+// private:
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.h]:
```suggestion
```

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 12]
```diff
@@ -197,7 +203,8 @@ MMCellFlag::FaceCrossingType MMCellFlag::faceCrossingType(Face face)
     return (FaceCrossingType::NoFaceCrossing);
   }
 }
-bool MMCellFlag::isEdgeCrossing(Edge edge)
+
+bool isEdgeCrossing(unsigned int& m_bitFlag, Edge edge)
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]: arg should not have the member variable naming scheme in a free function

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 13]
```diff
@@ -158,7 +164,7 @@ MMCellFlag::VertexType MMCellFlag::vertexType()
     return (VertexType::NoVertex);
   }
 }
-MMCellFlag::FaceCrossingType MMCellFlag::faceCrossingType(Face face)
+FaceCrossingType faceCrossingType(unsigned int& m_bitFlag, Face face)
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]: arg should not have the member variable naming scheme in a free function

File: src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp [hunk 14]
```diff
@@ -136,12 +142,12 @@ void MMCellFlag::set(int32_t cellLabels[8])
...
-}
+// unsigned char numJunctions() const
+//{
+//   return m_numJunctions;
+// }
 
-MMCellFlag::VertexType MMCellFlag::vertexType()
+VertexType vertexType(unsigned int& m_bitFlag)
 {
   unsigned int vertexTypeBits = (m_bitFlag & m_vertexTypeBits) >> VertexTypeShift;
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/src/SimplnxCore/SurfaceNets/MMCellFlag.cpp]: `m_vertexTypeBits` is seemingly undefined by the time we arrive here, if it is defined elsewhere as a constant of some sort it really should be changed to the typical `k_` naming schema

**Review by nyoungbq — CHANGES_REQUESTED** [review]

**Review by nyoungbq — APPROVED** [review]
