### PR TITLE
BUG: Use a Static Boolean to Register ITK Factories Once

### LINKED ISSUE #1447: BUG: ITKImageProcessingPlugin does not check if a factory has already been registered before registering it again.
ITKImageProcessingPlugin does not check if a factory has already been registered before registering it again, resulting in multiple registrations of the same factories and gradual slowdowns when executing a unit test many times in a row.  

Example: unit test that loads the plugins and then generates 270 SECTIONs (resulting in 270 separate runs of the entire test and subsequently 270 calls to load the plugins).

Also double check if this issue is affecting the other plugins and fix those too.

### PR DESCRIPTION
**Pull request by nyoungbq**
Fixes: #1447

### CODE REVIEW

File: src/Plugins/ITKImageProcessing/src/ITKImageProcessing/ITKImageProcessingPlugin.cpp [hunk 1]
```diff
@@ -34,7 +34,12 @@ ITKImageProcessingPlugin::ITKImageProcessingPlugin()
   {
     addFilter(filterFunc);
   }
-  RegisterITKImageIO();
+
+  if(!isRegistered)
+  {
+    RegisterITKImageIO();
+    isRegistered = true;
+  }
```
Comment (JDuffeyBQ) [inline src/Plugins/ITKImageProcessing/src/ITKImageProcessing/ITKImageProcessingPlugin.cpp]:
```suggestion
  static bool s_IsRegistered = false;
  if(!s_IsRegistered)
  {
    RegisterITKImageIO();
    s_IsRegistered = true;
  }
```
I would suggest moving the bool inside the function since it is only relevant to this spot.

**Review by JDuffeyBQ — CHANGES_REQUESTED** [review]

**Review by JDuffeyBQ — APPROVED** [review]
