### PR TITLE
BUG: Modernize Segment Features Feedback

### LINKED ISSUE #1433: BUG: Segment Features (Scalar) Progress percent calculation is incorrect.
```
[2025:09:15 16:14:09] [3/6] Multi-Threshold Objects: End
[2025:09:15 16:14:09] [4/6] Segment Features (Scalar): Begin
[2025:09:15 16:14:11] [4/6] Segment Features (Scalar): 28.50% - Features Found: 632
[2025:09:15 16:14:12] [4/6] Segment Features (Scalar): 42.20% - Features Found: 1304
[2025:09:15 16:14:13] [4/6] Segment Features (Scalar): 51.28% - Features Found: 1980
[2025:09:15 16:14:14] [4/6] Segment Features (Scalar): 62.06% - Features Found: 2661
[2025:09:15 16:14:15] [4/6] Segment Features (Scalar): 66.55% - Features Found: 3338
[2025:09:15 16:14:16] [4/6] Segment Features (Scalar): 79.14% - Features Found: 4004
[2025:09:15 16:14:17] [4/6] Segment Features (Scalar): 113.40% - Features Found: 4636
[2025:09:15 16:14:18] [4/6] Segment Features (Scalar): 133.03% - Features Found: 5294
[2025:09:15 16:14:19] [4/6] Segment Features (Scalar): 142.45% - Features Found: 5924
[2025:09:15 16:14:19] [4/6] Segment Features (Scalar): Total Features Found: 6028
[2025:09:15 16:14:19] [4/6] Segment Features (Scalar): Randomizing Feature Ids
[2025:09:15 16:14:21] [4/6] Segment Features (Scalar): End
[2025:09:15 16:14:21] [5/6] Create Surface Mesh (Surface Nets): Begin
[2025:09:15 16:16:16] [5/6] Create Surface Mesh (Surface Nets): End
[2025:09:15 16:16:16] f2e95864-20f4-4611-9604-99509d741c48: Execute Complete
```

This was segmenting a 500 x 500 x 500 image geometry

### PR DESCRIPTION
**Pull request by nyoungbq**
Fixes: #1433 

The calling function varies in size during execution, so completion percentage removed, but feedback every 1 second remains.

### CODE REVIEW

File: src/simplnx/Utilities/SegmentFeatures.cpp [hunk 1]
```diff
@@ -147,7 +147,7 @@ Result<> SegmentFeatures::execute(IGridGeometry* gridGeom)
     if(std::chrono::duration_cast<std::chrono::milliseconds>(now - start).count() > 1000)
```
Comment (imikejackson) [inline src/simplnx/Utilities/SegmentFeatures.cpp]: THis should be swapped out for the MessageHelper and ThrottledMessenger classes.

**Review by imikejackson — CHANGES_REQUESTED** [review]

**Review by imikejackson — APPROVED** [review]
