### PR TITLE
BUG: Fixes bug in BadDataNeighborOrientationCheck when finding the LaueOps instance

### LINKED ISSUE #1395: BUG: BadDataNeighborOrientationCheck crash
The variable `phase1` is shared between separate loops and if it's not set in the first loop it is invalid for the 2nd. This bug is not present in old DREAM3D. The solution is to separately acquire the value of `phase1` in each loop with no sharing.

### PR DESCRIPTION
**Pull request by imikejackson**
- Also brings consistency to all uses of the LaueOps classes to use 'laueClass' as a variable.
- Fixes bug where the phase value was indexing directly into orientation ops instead of going through crystal structures first in ComputeFeatureFaceMisorientation

### CODE REVIEW

File: src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ComputeFeatureFaceMisorientation.cpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ class CalculateFaceMisorientationColorsImpl
           quat2 = m_Quats[feature2 * 4 + 2];
           quat3 = m_Quats[feature2 * 4 + 3];
           QuatD q2(quat0, quat1, quat2, quat3);
-          OrientationD axisAngle = m_OrientationOps[phase1]->calculateMisorientation(q1, q2);
+          OrientationD axisAngle = m_OrientationOps[m_CrystalStructures[phase1]]->calculateMisorientation(q1, q2);
```
Comment (JDuffeyBQ) [inline src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ComputeFeatureFaceMisorientation.cpp:79]: Is this also a bug fix?

Comment (imikejackson) [reply src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ComputeFeatureFaceMisorientation.cpp:79]: yes

Comment (imikejackson) [reply src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ComputeFeatureFaceMisorientation.cpp:79]: yes

Comment (JDuffeyBQ) [reply src/Plugins/OrientationAnalysis/src/OrientationAnalysis/Filters/Algorithms/ComputeFeatureFaceMisorientation.cpp:79]: I'll update the description to also mention this one.

**Review by JDuffeyBQ — APPROVED** [review]
