### PR TITLE
BUG: Data Fusion Pipeline Fixes

### LINKED ISSUE #549: Kernel Avg Misorientation needs user feedback
Since this is multi-threaded, we can reuse an implementation from another multi threaded filter.

### PR DESCRIPTION
**Pull request by imikejackson**
These are fixes to allow the Data Fusion pipelines to run to completion.

### CODE REVIEW

File: src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp [hunk 1]
```diff
@@ -84,13 +90,14 @@ Parameters RemoveFlaggedVertices::parameters() const
...
-  params.insert(std::make_unique<ArraySelectionParameter>(k_MaskPath_Key, "Mask Array", "DataPath to the conditional array that will be used to decide which vertices are removed.", DataPath(),
-                                                          ArraySelectionParameter::AllowedTypes{DataType::boolean}, ArraySelectionParameter::AllowedComponentShapes{{1}}));
-  params.insert(
-      std::make_unique<DataGroupCreationParameter>(k_ReducedVertexPath_Key, "Reduced Vertex Geometry", "Created Vertex Geometry DataPath. This will be created during the filter.", DataPath()));
-  params.insert(std::make_unique<DataObjectNameParameter>(k_VertexDataName_Key, "Vertex Data Name", "Name of the vertex data AttributeMatrix", INodeGeometry0D::k_VertexDataName));
+  //  params.insert(std::make_unique<MultiArraySelectionParameter>(k_ArraySelection_Key, "Vertex Data Arrays To Copy", "Paths to the target Vertex DataArrays to also reduce.", std::vector<DataPath>(),
+  //                                                               MultiArraySelectionParameter::AllowedTypes{IArray::ArrayType::DataArray}, complex::GetAllDataTypes()));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp]:
```suggestion
```
Not sure why these are commented out if they are unused in the newest version of the filter

File: src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp [hunk 2]
```diff
@@ -84,13 +90,14 @@ Parameters RemoveFlaggedVertices::parameters() const
...
+  params.insert(std::make_unique<ArraySelectionParameter>(k_MaskPath_Key, "Flagged Vertex Array", "DataPath to the conditional array that will be used to decide which vertices are removed.",
+                                                          DataPath(), ArraySelectionParameter::AllowedTypes{DataType::boolean}, ArraySelectionParameter::AllowedComponentShapes{{1}}));
+  params.insertSeparator(Parameters::Separator{"Newly Reduced Geometry"});
+  params.insert(std::make_unique<DataGroupCreationParameter>(k_ReducedVertexGeometryPath_Key, "Reduced Vertex Geometry", "Created Vertex Geometry DataPath. This will be created during the filter.",
+                                                             DataPath()));
+  // params.insert(std::make_unique<DataObjectNameParameter>(k_VertexDataName_Key, "Vertex Data Name", "Name of the vertex data AttributeMatrix", INodeGeometry0D::k_VertexDataName));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp]:
```suggestion
```

File: src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp [hunk 3]
```diff
@@ -104,113 +111,163 @@ IFilter::PreflightResult RemoveFlaggedVertices::preflightImpl(const DataStructur
 {
   auto vertexGeomPath = filterArgs.value<DataPath>(k_VertexGeomPath_Key);
   auto maskArrayPath = filterArgs.value<DataPath>(k_MaskPath_Key);
-  auto targetArrayPaths = filterArgs.value<std::vector<DataPath>>(k_ArraySelection_Key);
-  auto reducedVertexPath = filterArgs.value<DataPath>(k_ReducedVertexPath_Key);
-  auto vertexDataName = filterArgs.value<std::string>(k_VertexDataName_Key);
+  // auto targetArrayPaths = filterArgs.value<std::vector<DataPath>>(k_ArraySelection_Key);
+  auto reducedVertexPath = filterArgs.value<DataPath>(k_ReducedVertexGeometryPath_Key);
+  // auto vertexDataName = filterArgs.value<std::string>(k_VertexDataName_Key);
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.cpp]:
```suggestion
  auto reducedVertexPath = filterArgs.value<DataPath>(k_ReducedVertexGeometryPath_Key);
```

File: src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.hpp [hunk 4]
```diff
@@ -26,9 +26,9 @@ class COMPLEXCORE_EXPORT RemoveFlaggedVertices : public IFilter
   // Parameter Keys
   static inline constexpr StringLiteral k_VertexGeomPath_Key = "vertex_geom";
   static inline constexpr StringLiteral k_MaskPath_Key = "mask";
-  static inline constexpr StringLiteral k_ArraySelection_Key = "target_arrays";
-  static inline constexpr StringLiteral k_ReducedVertexPath_Key = "reduced_vertex";
-  static inline constexpr StringLiteral k_VertexDataName_Key = "vertex_data_name";
+  //  static inline constexpr StringLiteral k_ArraySelection_Key = "target_arrays";
+  static inline constexpr StringLiteral k_ReducedVertexGeometryPath_Key = "reduced_vertex";
+  //  static inline constexpr StringLiteral k_VertexDataName_Key = "vertex_data_name";
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/src/ComplexCore/Filters/RemoveFlaggedVertices.hpp]:
```suggestion
  static inline constexpr StringLiteral k_ReducedVertexGeometryPath_Key = "reduced_vertex";
```

File: src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp [hunk 5]
```diff
@@ -16,10 +16,10 @@ TEST_CASE("ComplexCore::RemoveFlaggedVertices: Instantiate", "[ComplexCore][Remo
   Arguments args;
 
   args.insertOrAssign(RemoveFlaggedVertices::k_VertexGeomPath_Key, std::make_any<DataPath>());
-  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(std::vector<DataPath>{}));
+  //  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(std::vector<DataPath>{}));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp]:
```suggestion
```

File: src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp [hunk 6]
```diff
@@ -16,10 +16,10 @@ TEST_CASE("ComplexCore::RemoveFlaggedVertices: Instantiate", "[ComplexCore][Remo
...
   args.insertOrAssign(RemoveFlaggedVertices::k_MaskPath_Key, std::make_any<DataPath>());
-  args.insertOrAssign(RemoveFlaggedVertices::k_ReducedVertexPath_Key, std::make_any<DataPath>());
-  args.insertOrAssign(RemoveFlaggedVertices::k_VertexDataName_Key, std::make_any<std::string>("Vertex Data"));
+  args.insertOrAssign(RemoveFlaggedVertices::k_ReducedVertexGeometryPath_Key, std::make_any<DataPath>());
+  // args.insertOrAssign(RemoveFlaggedVertices::k_VertexDataName_Key, std::make_any<std::string>("Vertex Data"));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp]:
```suggestion
```

File: src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp [hunk 7]
```diff
@@ -71,10 +71,10 @@ TEST_CASE("ComplexCore::RemoveFlaggedVertices: Test Algorithm", "[ComplexCore][R
   DataPath reducedVertexAMPath = reducedVertexPath.createChildPath(Constants::k_VertexDataGroupName);
 
   args.insertOrAssign(RemoveFlaggedVertices::k_VertexGeomPath_Key, std::make_any<DataPath>(vertexGeomPath));
-  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(arraySelection));
+  //  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(arraySelection));
   args.insertOrAssign(RemoveFlaggedVertices::k_MaskPath_Key, std::make_any<DataPath>(maskPath));
-  args.insertOrAssign(RemoveFlaggedVertices::k_ReducedVertexPath_Key, std::make_any<DataPath>(reducedVertexPath));
-  args.insertOrAssign(RemoveFlaggedVertices::k_VertexDataName_Key, std::make_any<std::string>(Constants::k_VertexDataGroupName));
+  args.insertOrAssign(RemoveFlaggedVertices::k_ReducedVertexGeometryPath_Key, std::make_any<DataPath>(reducedVertexPath));
+  // args.insertOrAssign(RemoveFlaggedVertices::k_VertexDataName_Key, std::make_any<std::string>(Constants::k_VertexDataGroupName));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp]:
```suggestion
```

File: src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp [hunk 8]
```diff
@@ -71,10 +71,10 @@ TEST_CASE("ComplexCore::RemoveFlaggedVertices: Test Algorithm", "[ComplexCore][R
   DataPath reducedVertexAMPath = reducedVertexPath.createChildPath(Constants::k_VertexDataGroupName);
 
   args.insertOrAssign(RemoveFlaggedVertices::k_VertexGeomPath_Key, std::make_any<DataPath>(vertexGeomPath));
-  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(arraySelection));
+  //  args.insertOrAssign(RemoveFlaggedVertices::k_ArraySelection_Key, std::make_any<std::vector<DataPath>>(arraySelection));
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/test/RemoveFlaggedVerticesTest.cpp]:
```suggestion
```

File: src/Plugins/ComplexCore/src/ComplexCore/Filters/ApplyTransformationToGeometryFilter.cpp [hunk 9]
```diff
@@ -161,7 +162,8 @@ IFilter::PreflightResult ApplyTransformationToGeometryFilter::preflightImpl(cons
     {
       return {MakeErrorResult<OutputActions>(-82010, fmt::format("Precomputed transformation matrix must have a valid path. Invalid path given: '{}'", pComputedTransformationMatrixPath.toString()))};
     }
-    transformationMatrix = ImageRotationUtilities::CopyPrecomputedToTransformationMatrix(*precomputedMatrixPtr);
+    // transformationMatrix = ImageRotationUtilities::CopyPrecomputedToTransformationMatrix(*precomputedMatrixPtr);
```
Comment (nyoungbq) [inline src/Plugins/ComplexCore/src/ComplexCore/Filters/ApplyTransformationToGeometryFilter.cpp]:
```suggestion
```

**Review by nyoungbq — APPROVED** [review]
Just remove all the excess commented out code and its set to merge
