### PR TITLE
BUG: Laplacian was not releasing internal connectivity arrays. Now smooth edges, Hex and Tet Geometries

### LINKED ISSUE #1422: Laplacian Smoothing Filter leaves edge data inside the Triangle Geometry
This can mess with the rendering side of things.

### PR DESCRIPTION
**Pull request by imikejackson**
- The algorithm left the internal "Edge" data arrays (connectivity) - FIXED
- We can now smooth Edge, Triangle, Quad, Tet and Hex meshes.

### CODE REVIEW

File: src/Plugins/SimplnxCore/test/LaplacianSmoothingFilterTest.cpp [hunk 1]
```diff
@@ -112,11 +111,8 @@ TEST_CASE("SimplnxCore::LaplacianSmoothingFilter", "[SurfaceMeshing][LaplacianSm
   }
 
 #ifdef SIMPLNX_WRITE_TEST_OUTPUT
-  Result<nx::core::HDF5::FileWriter> result = nx::core::HDF5::FileIO::WriteFile(fmt::format("{}/LaplacianSmoothing.dream3d", unit_test::k_BinaryTestOutputDir));
-  nx::core::HDF5::FileWriter fileWriter = std::move(result.value());
-
-  auto resultH5 = HDF5::DataStructureWriter::WriteFile(dataStructure, fileWriter);
-  SIMPLNX_RESULT_REQUIRE_VALID(resultH5);
+  std::cout << "Writing File: " << fmt::format("{}/laplacian_smoothing_test.dream3d", unit_test::k_BinaryTestOutputDir) << "\n";
```
Comment (nyoungbq) [inline src/Plugins/SimplnxCore/test/LaplacianSmoothingFilterTest.cpp]: Is this line left here intentionally?

**Review by nyoungbq — APPROVED** [review]
